
Dataset <- read.table("C:/Users/Jessica/Documents/MINERIA DE DATOS/lifestyle-dataset.tsv", header=TRUE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE)
with(Dataset, Hist(Armonia.Ambiente, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Armonia.Ambiente, groups=Residencia, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Barplot(Residencia, xlab="Residencia", ylab="Frequency"))
with(Dataset, Hist(Conocer.Personas, groups=Residencia, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Pref.Aire.Libre, groups=Residencia, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Disfruta.Naturaleza, groups=Residencia, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Relacion.Clima, groups=Residencia, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Ejercicio.Regular, groups=Residencia, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Disfruta.Naturaleza, groups=Residencia, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Pref.Aire.Libre, groups=Residencia, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Relacion.Clima, groups=Residencia, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Armonia.Ambiente, groups=Residencia, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Conocer.Personas, groups=Residencia, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, (t.test(Pref.Aire.Libre, alternative='two.sided', mu=0.0, conf.level=.95)))
with(Dataset, (t.test(Pref.Aire.Libre, alternative='greater', mu=3.0, conf.level=.95)))
with(Dataset, (t.test(Disfruta.Naturaleza, alternative='greater', mu=3.5, conf.level=.95)))
mujeres <- subset(Dataset, subset=Sexo=="Mujer")
with(mujeres, (t.test(Pref.Aire.Libre, alternative='greater', mu=2, conf.level=.95)))
with(mujeres, (t.test(Pref.Aire.Libre, alternative='greater', mu=3, conf.level=.95)))
hombres <- subset(Dataset, subset=Sexo=="Hombre")
with(hombres, tapply(Pref.Aire.Libre, Sexo,  var, na.rm=TRUE))
var.test(Pref.Aire.Libre ~ Sexo, alternative='two.sided', conf.level=.95, data=hombres)
with(Dataset, tapply(Pref.Aire.Libre, Sexo,  var, na.rm=TRUE))
var.test(Pref.Aire.Libre ~ Sexo, alternative='two.sided', conf.level=.95, data=Dataset)
t.test(Pref.Aire.Libre~Sexo, alternative='two.sided', conf.level=.95, var.equal=FALSE, data=Dataset)
with(hombres, (t.test(Pref.Aire.Libre, alternative='two.sided', mu=0.0, conf.level=.95)))
library(abind, pos=14)
library(e1071, pos=15)
densityPlot(Disfruta.Naturaleza~Sexo, data=Dataset, bw="SJ", adjust=1, kernel="gaussian")
t.test(Pref.Aire.Libre~Sexo, alternative='two.sided', conf.level=.95, var.equal=TRUE, data=Dataset)
densityPlot(Conocer.Personas~Sexo, data=Dataset, bw="SJ", adjust=1, kernel="gaussian")
densityPlot(Disfruta.Naturaleza~Sexo, data=Dataset, bw="SJ", adjust=1, kernel="gaussian")
with(Dataset, (t.test(Conocer.Personas, Disfruta.Naturaleza, alternative='two.sided', conf.level=.95, paired=TRUE)))
with(Dataset, (t.test(Disfruta.Naturaleza, alternative='two.sided', mu=0.0, conf.level=.95)))
with(Dataset, (t.test(Relacion.Clima, alternative='two.sided', mu=0.0, conf.level=.95)))
with(Dataset, (t.test(Disfruta.Naturaleza, alternative='greater', mu=3.6, conf.level=.95)))
with(Dataset, plotMeans(Conocer.Personas, Sexo, error.bars="se", connect=TRUE))
library(tcltk, pos=16)
library(aplpack, pos=16)
library(colorspace, pos=18)
with(Dataset, Barplot(Sexo, xlab="Sexo", ylab="Frequency"))
stripchart(Conocer.Personas ~ Sexo, vertical=TRUE, method="stack", ylab="Conocer.Personas", data=Dataset)
with(Dataset, (t.test(Conocer.Personas, alternative='two.sided', mu=0, conf.level=.95)))
with(Dataset, (t.test(Relacion.Clima, alternative='greater', mu=3.866667, conf.level=.95)))
with(Dataset, Hist(Disfruta.Naturaleza, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Relacion.Clima, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, (t.test(Ejercicio.Regular, alternative='two.sided', mu=0, conf.level=.95)))
with(Dataset, (t.test(Armonia.Ambiente, alternative='greater', mu=3.6, conf.level=.95)))
with(Dataset, Hist(Disfruta.Naturaleza, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Conocer.Personas, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Armonia.Ambiente, scale="frequency", breaks="Sturges", col="darkgray"))
with(Dataset, Hist(Ejercicio.Regular, scale="frequency", breaks="Sturges", col="darkgray"))

